---
name: Backup Drop Zone AMI
run-name: Backup Drop Zone AMI backup-drop-zone-primer-(date-time) by @${{ github.actor }}

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  backup-drop-zone-ami:
    uses: nationalarchives/ds-github-actions/.github/workflows/backup-drop-zone-ami-build.yml@main
    with:
      base_role: "arn:aws:iam::637423167251:role/gha-oidc-role"
      playbook_role: "arn:aws:iam::637423167251:role/gha-devops-role"
      region: "eu-west-2"
      key_name: "backup-drop-zone-eu-west-2"
      instance_type: "t3a.small"
      volume_size: 40
...
